name: API CI Tests

on: 
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [17.x]
      
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      
      - name: Install deps
        run: pnpm --filter api install --frozen-lockfile
      - run: pnpm i -g typescript prisma
      
      - name: Run tests
        run: pnpm test